'type: breaking': ['breaking/*']
'type: feature': ['feature/*', 'features/*', 'feat/*']
'type: improvement': ['improve/*', 'improvement/*', 'improvements/*', 'impr/*']
'type: automation': ['automation/*']

skip-changelog: ['main']
