'type: breaking': ['breaking/*']
'type: feature': ['feature/*', 'features/*', 'feat/*', 'feature-*']
'type: improvement': ['improve/*', 'improvement/*', 'improvements/*', 'impr/*']
'type: automation': ['automation/*']
'type: documentation': ['doc/*', 'docs/*', 'documentation/*', 'documentations/*']

skip-changelog: ['main']
