name: Pritunl Client GitHub Action
description: Establish a Pritunl VPN connection using the Pritunl Client that supports OpenVPN and WireGuard modes on GitHub Actions.


inputs:
  profile-file:
    description: 'The corporate provided or self-obtained Pritunl Profile Key file.'
    required: true
    default:

  profile-pin:
    description: 'The Pritunl Profile PIN/Password if provided.'
    required: false
    default:

  vpn-mode:
    description: 'The VPN mode from the two choices is `ovpn` for OpenVPN or `wg` for WireGuard.'
    required: false
    default: ovpn

  client-version:
    description: 'The Version of Pritunl Client to use.'
    required: false
    default: prebuilt-apt-repo

  start-connection:
    description: 'Start the VPN Connection Automatically.'
    required: false
    default: true


outputs:
  client-id:
    description: "Pritunl Client ID"
    value: ${{ steps.pritunl-client.outputs.client-id }}


runs:
  using: "composite"
  steps:
    - name: Setup Temporary Directory
      run: |
        echo "TEMPDIR=$(mktemp -d)" >> "$GITHUB_ENV"
      shell: bash

    - name: Install Pritunl Client from Prebuilt Apt Repo (for Latest Version)
      if: ${{ inputs.client-version == 'prebuilt-apt-repo' }}
      run: |
        sudo tee /etc/apt/sources.list.d/pritunl.list << EOF
        deb https://repo.pritunl.com/stable/apt $(lsb_release -cs) main
        EOF
        sudo apt-get --assume-yes install gnupg
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A | sudo tee /etc/apt/trusted.gpg.d/pritunl.asc
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install pritunl-client
      shell: bash

    - name: Install Pritunl Client from GitHub Releases (for Version Specific)
      if: ${{ inputs.client-version != 'prebuilt-apt-repo' }}
      run: |
        curl -sL https://github.com/pritunl/pritunl-client-electron/releases/download/${{ inputs.client-version }}/pritunl-client_${{ inputs.client-version }}-0ubuntu1.$(lsb_release -cs)_amd64.deb \
          -o ${{ env.TEMPDIR }}/pritunl-client.deb
        sudo apt-get --assume-yes install -f ${{ env.TEMPDIR }}/pritunl-client.deb
      shell: bash

    - name: Install OpenVPN Dependencies for `ovpn` VPN Mode
      if: ${{ inputs.vpn-mode == 'ovpn' }}
      run: |
        sudo apt-get --assume-yes install openvpn-systemd-resolved
      shell: bash

    - name: Install WireGuard Dependencies for `wg` VPN Mode
      if: ${{ inputs.vpn-mode == 'wg' }}
      run: |
        sudo apt-get --assume-yes install wireguard-tools
      shell: bash

    - name: Load the Pritunl Profile to the Client
      id: pritunl-client
      run: |
        # Save the `base64` file format and convert it back to `tar` binary.
        echo "${{ inputs.profile-file }}" > ${{ env.TEMPDIR }}/profile-file.base64
        base64 --decode ${{ env.TEMPDIR }}/profile-file.base64 > ${{ env.TEMPDIR }}/profile-file.tar
        # Add the Profile File to Pritunl Client
        pritunl-client add ${{ env.TEMPDIR }}/profile-file.tar
        # Set `client-id` as step output
        client_id=$(
          pritunl-client list \
            | awk -F'|' 'NR==4{print $2}' \
            | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//'
          )
        echo "client-id=$client_id" >> $GITHUB_OUTPUT
        # Disable autostart option
        pritunl-client disable $client_id
      shell: bash

    - name: Starting a VPN Connection
      if: ${{ inputs.start-connection == 'true' }}
      run: |
        # Start the Connection
        pritunl-client start \
          ${{ steps.pritunl-client.outputs.client-id }} \
          --mode ${{ inputs.vpn-mode }} \
          $(
            pritunl_pin='${{ inputs.profile-pin }}'
            if [[ "$pritunl_pin" ]]; then
              echo "--password $pritunl_pin"
            fi
          )
        # Check the Connection
        echo "Waiting for your IP address and connection to be fully active."
        check_connection_attemp=0
        check_loading_indicator=""
        until pritunl-client list \
          | awk -F '|' 'NR==4{print $8}' \
          | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' \
          | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?$' --color=never
        do
          check_connection_attemp=$((check_connection_attemp+1))
          check_loading_indicator+="."
          echo "Check connection attempt: $check_connection_attemp $check_loading_indicator"
          sleep 1
        done
        # Show VPN Connection Status
        pritunl-client list
      shell: bash


branding:
  icon: server
  color: gray-dark
