# Define the GitHub Action
name: Pritunl Client GitHub Action
description: Establish automated secure Pritunl VPN connections with Pritunl Client in GitHub Actions, supporting OpenVPN and WireGuard.

# Define branding for the GitHub Marketplace
branding:
  icon: server
  color: gray-dark

# Define inputs for the Action
inputs:
  profile-file:
    description: Pritunl Profile Key file
    required: true
    default: ''

  profile-pin:
    description: Pritunl Profile PIN/Password
    required: false
    default: ''

  profile-server:
    description: Pritunl Profile Server (for specifying a particular server or multiple servers within a profile)
    required: false
    default: ''

  vpn-mode:
    description: VPN mode (ovpn for OpenVPN or wg for WireGuard)
    required: false
    default: 'ovpn'

  client-version:
    description: Pritunl Client version (defaults to package manager version)
    required: false
    default: 'from-package-manager'

  start-connection:
    description: Start VPN connection automatically (true/false)
    required: false
    default: 'true'

  ready-profile-timeout:
    description: Wait for Ready Profile timeout (seconds)
    required: false
    default: '3'

  established-connection-timeout:
    description: Wait for Established Connection timeout (seconds)
    required: false
    default: '30'

  concealed-outputs:
    description: Concealed Outputs (true/false)
    required: false
    default: 'true'

# Define outputs for the Action
outputs:
  client-id:
    description: Primary Client ID (string, bash variable)
    value: ${{ steps.pritunl-client.outputs.client-id }}

  client-ids:
    description: All Client IDs and Names (JSON array)
    value: ${{ steps.pritunl-client.outputs.client-ids }}

# Define the Action's workflow
runs:
  using: "composite"
  steps:
    - name: Setup Pritunl Client
      id: pritunl-client
      env:
        # Set environment variables for input values
        PRITUNL_PROFILE_FILE: ${{ inputs.profile-file }}
        PRITUNL_PROFILE_PIN: ${{ inputs.profile-pin }}
        PRITUNL_PROFILE_SERVER: ${{ inputs.profile-server }}
        PRITUNL_VPN_MODE: ${{ inputs.vpn-mode }}
        PRITUNL_CLIENT_VERSION: ${{ inputs.client-version }}
        PRITUNL_START_CONNECTION: ${{ inputs.start-connection }}
        PRITUNL_READY_PROFILE_TIMEOUT: ${{ inputs.ready-profile-timeout }}
        PRITUNL_ESTABLISHED_CONNECTION_TIMEOUT: ${{ inputs.established-connection-timeout }}
        PRITUNL_CONCEALED_OUTPUTS: ${{ inputs.concealed-outputs }}
      shell: bash
      run: |
        # Entrypoint for executing 'pritunl-client.sh' script

        # Define the pritunl_client function
        pritunl_client() {
          # Declare a local variable to store the path separator
          # (using a local variable to avoid polluting the global namespace)
          local separator

          # Determine the path separator based on the runner OS
          case "${RUNNER_OS}" in
            Windows)
              # Use a backslash (\) for Windows (required for Windows paths)
              separator='\'
              ;;
            *)
              # Catch-all for non-Windows OSes (Linux, macOS, etc.)
              # Use a forward slash (/) for paths
              separator='/'
              ;;
          esac

          # Construct and run the full path to the 'pritunl-client.sh' script
          # using the GITHUB_ACTION_PATH and the separator
          "${GITHUB_ACTION_PATH}${separator}pritunl-client.sh"
        }

        # Call the pritunl_client function to start the script
        pritunl_client
