name: Test Connection

on:
  workflow_dispatch:

jobs:
  test-connection:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
          - windows-2022
          - windows-2019
        vpn:
          - ovpn
          - wg
        client-version:
          - 'from-package-manager'
          - 1.3.3637.72
        start-connection:
          - 'true'
          - 'false'

    runs-on: ${{ matrix.os }}
    name: "run:${{ matrix.os }}, vpn:${{ matrix.vpn }}, cv:${{ matrix.client-version }}, sc:${{ matrix.start-connection }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pritunl Profile
        id: pritunl-connection
        uses: ./
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
          vpn-mode: ${{ matrix.vpn }}
          client-version: ${{ matrix.client-version }}
          start-connection: ${{ matrix.start-connection }}

      - name: Starting a VPN Connection Manually
        if: ${{ matrix.start-connection == 'false' }}
        shell: bash
        run: |
          # Start the VPN Connection Manually
          pritunl-client start ${{ steps.pritunl-connection.outputs.client-id }} \
            --password ${{ secrets.PRITUNL_PROFILE_PIN || '' }} \
            --mode ${{ matrix.vpn }}

      - name: Show VPN Connection Status Manually
        if: ${{ matrix.start-connection == 'false' }}
        shell: bash
        run: |
          # Waiting for Established Connection
          CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-30}
          wait_established_connection() {
            # Define the total number of steps
            local total_steps="${CONNECTION_TIMEOUT}"

            # Initialize the progress variable
            local progress=1

            # Clear the initial line
            echo -n -e "\r\033[K"

            # Loop until the progress reaches the total number of steps
            while [[ "$progress" -le "$total_steps" ]]; do
              if pritunl-client list |
                awk -F '|' 'NR==4{print $8}' |
                sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' |
                grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?$' --quiet --color=never; then
                  echo "Connection established..."
                  break
              else
                # Calculate the percentage progress
                percentage=$((progress * 100 / total_steps))

                # Calculate the number of completed and remaining characters for the progress bar
                completed=$((percentage / 2))
                remaining=$((50 - completed))

                # Print the connection check progress on the same line
                echo -n -e "Establishing connection: ["
                for ((i = 0; i < completed; i++)); do
                    echo -n -e "#"
                done
                for ((i = 0; i < remaining; i++)); do
                    echo -n -e "-"
                done
                echo -n -e "] checking $progress out of $total_steps total connection timeout"

                # Increment the progress
                progress=$((progress + 1))

                # Sleep for a moment (simulating work)
                sleep 1

                # Clear the line again for the next update
                echo -n -e "\r\033[K"

                # Print the timeout message and exit error
                if [[ "$progress" -ge "$total_steps" ]]; then
                  echo "Timeout reached! Exiting..."
                  exit 1
                fi
              fi
            done

            # Print a newline to end the progress loader
            echo ""
          }

          # Waiting for Established Connection
          wait_established_connection

          # Display VPN Connection Status
          display_connection_status() {
            local pritunl_client_info=$(pritunl-client list)
            local profile_name=$(echo "$pritunl_client_info" | awk -F '|' 'NR==4{print $3}' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
            local profile_ip=$(echo "$pritunl_client_info" | awk -F '|' 'NR==4{print $8}' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
            echo "Connected as '$profile_name' with a private address of '$profile_ip'."
          }

          # Display VPN Connection Status
          display_connection_status

      - name: Install IP Tooling (IP Calculator)
        shell: bash
        run: |
          # Install IP Calculator
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install --assume-yes ipcalc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ipcalc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            curl -sL "https://raw.githubusercontent.com/kjokjo/ipcalc/0.51/ipcalc" -o $HOME/bin/ipcalc
            chmod +x $HOME/bin/ipcalc
          fi

          # Validate the IP Calculator Installation
          echo "ipcalc version: $(ipcalc --version)"

      - name: VPN Gateway Reachability Test
        shell: bash
        run: |
          # Ping VPN Gateway
          PING_FLAG="$([[ "$RUNNER_OS" == "Windows" ]] && echo "-n 10" || echo "-c 10")"
          HOST="$(pritunl-client list | awk -F '|' 'NR==4{print $8}' | xargs ipcalc | awk 'NR==6{print $2}')"

          # Ping VPN Gateway
          ping $PING_FLAG $HOST

      - name: Stop VPN Connection Manually
        shell: bash
        if: ${{ matrix.start-connection == 'false' }}
        run: |
          # Stop Connection Manually
          pritunl-client stop ${{ steps.pritunl-connection.outputs.client-id }}
