name: Test Connection

on:
  workflow_dispatch:
    inputs:
      client_version:
        description: 'Pritunl Client Version'
        type: choice
        options:
        - 'package-manager'
        - 1.3.3600.11
        - 1.3.3596.68

      start_connection:
        description: 'Start Connection'
        type: boolean
        default: true

jobs:
  test-connection:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
          - windows-2022
          - windows-2019
        vpn:
          - ovpn
          - wg
    runs-on: ${{ matrix.os }}
    name: "run:${{ matrix.os }}, vpn:${{ matrix.vpn }}, cv:${{ github.event.inputs.client_version }}, sc:${{ github.event.inputs.start_connection }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pritunl Profile
        id: pritunl-connection
        uses: ./
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
          vpn-mode: ${{ matrix.vpn }}
          client-version: ${{ github.event.inputs.client_version }}
          start-connection: ${{ github.event.inputs.start_connection }}

      - name: Starting a VPN Connection and Show Status Manually
        if: ${{ github.event.inputs.start_connection == 'false' }}
        shell: bash
        run: |
          # Start the VPN Connection Manually
          pritunl-client start ${{ steps.pritunl-connection.outputs.client-id }} \
            --password ${{ secrets.PRITUNL_PROFILE_PIN || '' }} \
            --mode ${{ matrix.vpn }}

          CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-30}
          # Waiting for Established Connection
          wait_established_connection() {
            # Define the total number of steps
            local total_steps="${CONNECTION_TIMEOUT}"

            # Initialize the progress variable
            local progress=1

            # Clear the initial line
            echo -n -e "\r\033[K"

            # Loop until the progress reaches the total number of steps
            while [[ "$progress" -le "$total_steps" ]]; do
              if pritunl-client list |
                awk -F '|' 'NR==4{print $8}' |
                sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' |
                grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?$' --quiet --color=never; then
                echo "Connection established..."
                break
              else
                # Calculate the percentage progress
                percentage=$((progress * 100 / total_steps))

                # Calculate the number of completed and remaining characters for the progress bar
                completed=$((percentage / 2))
                remaining=$((50 - completed))

                # Print the connection check progress on the same line
                echo -n -e "Establishing connection: ["
                for ((i = 0; i < completed; i++)); do
                    echo -n -e "#"
                done
                for ((i = 0; i < remaining; i++)); do
                    echo -n -e "-"
                done
                echo -n -e "] checking $progress out of $total_steps total connection timeout"

                # Increment the progress
                progress=$((progress + 1))

                # Sleep for a moment (simulating work)
                sleep 1

                # Clear the line again for the next update
                echo -n -e "\r\033[K"

                # Print the timeout message and exit error
                if [[ "$progress" -ge "$total_steps" ]]; then
                  echo "Timeout reached! Exiting..."
                  exit 1
                fi
              fi
            done

            # Print a newline to end the progress loader
            echo ""
          }

          # Waiting for Established Connection
          wait_established_connection

          # Display VPN Connection Status
          pritunl_client_info=$(pritunl-client list)
          profile_name=$(echo "$pritunl_client_info" | awk -F '|' 'NR==4{print $3}' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
          profile_ip=$(echo "$pritunl_client_info" | awk -F '|' 'NR==4{print $8}' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
          echo "Connected as '$profile_name' with a private address of '$profile_ip'."

      - name: Install IP Tooling and VPN Gateway Reachability Test
        shell: bash
        run: |
          # Install IP Tooling (IP Calculator)
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install --assume-yes ipcalc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ipcalc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            curl -sL "https://raw.githubusercontent.com/kjokjo/ipcalc/0.51/ipcalc" -o $HOME/bin/ipcalc
            chmod +x $HOME/bin/ipcalc
          fi

          # VPN Gateway Reachability Test
          HOST="$(pritunl-client list | awk -F '|' 'NR==4{print $8}' | xargs ipcalc | awk 'NR==6{print $2}')"
          PING_FLAG="$([[ "$RUNNER_OS" == "Windows" ]] && echo "-n 10" || echo "-c 10")"

          ping $HOST $PING_FLAG

      - name: Stop VPN Connection Manually
        shell: bash
        if: ${{ github.event.inputs.start_connection == 'false' }}
        run: |
          pritunl-client stop ${{ steps.pritunl-connection.outputs.client-id }}
