name: Test Connection

on:
  workflow_dispatch:
    inputs:
      vpn_mode:
        description: 'VPN Mode'
        type: choice
        options:
        - ovpn
        - wg

      client_version:
        description: 'Pritunl Client Version'
        type: choice
        options:
        - 'package-manager'
        - 1.3.3600.11
        - 1.3.3596.68

      start_connection:
        description: 'Start Connection'
        type: boolean
        default: true

jobs:
  test-connection:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
          - windows-2022
          - windows-2019
    runs-on: ${{ matrix.os }}
    name: Runs on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pritunl Profile
        id: pritunl-connection
        uses: ./
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
          vpn-mode: ${{ github.event.inputs.vpn_mode }}
          client-version: ${{ github.event.inputs.client_version }}
          start-connection: ${{ github.event.inputs.start_connection }}

      - name: Starting a VPN Connection Manually
        if: ${{ github.event.inputs.start_connection == 'false' }}
        shell: bash
        run: |
          pritunl-client start ${{ steps.pritunl-connection.outputs.client-id }} \
            --password ${{ secrets.PRITUNL_PROFILE_PIN || '' }} \
            --mode ${{ github.event.inputs.vpn_mode }}

      - name: Show VPN Connection Status Manually
        if: ${{ github.event.inputs.start_connection == 'false' }}
        shell: bash
        run: |
          # Check the Connection
          echo "Waiting for your IP address and connection to be fully active"
          check_connection_attemp=0
          check_loading_indicator=""
          until pritunl-client list \
            | awk -F '|' 'NR==4{print $8}' \
            | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' \
            | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?$' --color=never
          do
            check_connection_attemp=$((check_connection_attemp+1))
            check_loading_indicator+="."
            echo Check connection attemp: $check_connection_attemp $check_loading_indicator
            sleep 1
          done
          # Show VPN Connection Status
          pritunl-client list

      - name: Install IP Tooling
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install --assume-yes ipcalc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ipcalc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            curl -sSL "https://github.com/kjokjo/ipcalc/archive/0.51.tar.gz" | tar -xzO "ipcalc-0.51/ipcalc" > $HOME/bin/ipcalc
            chmod +x $HOME/bin/ipcalc
          fi

      - name: VPN Gateway Reachability Test
        shell: bash
        run: |
          ping \
            $(
              pritunl-client list \
                | awk -F '|' 'NR==4{print $8}' \
                | xargs ipcalc \
                | awk 'NR==6{print $2}'
            ) \
            $(
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                echo "-n 10"
              else
                echo "-c 10"
              fi
            )

      - name: Stop VPN Connection Manually
        shell: bash
        if: ${{ github.event.inputs.start_connection == 'false' }}
        run: |
          pritunl-client stop ${{ steps.pritunl-connection.outputs.client-id }}
